Parse release handle, support release_type, slack msgs

diff --git a/.github/actions/slack-notification/action.yml b/.github/actions/slack-notification/action.yml
--- a/.github/actions/slack-notification/action.yml
+++ b/.github/actions/slack-notification/action.yml
@@ -1,4 +1,7 @@
 inputs:
+  slack_func:
+    description: 'Slack message format function to use'
+    required:  true
   release_tag:
     description: 'Release tag to build'
     required: true
@@ -11,6 +14,9 @@ inputs:
   packages_json:
     description: 'JSON structure of uploaded packages by distribution and architecture'
     required: true
+  message:
+    description: 'Message to send in case of failure'
+    required: false
   SLACK_WEB_HOOK_URL:
     description: 'Slack web hook URL'
     required: true
@@ -19,6 +25,7 @@ runs:
   using: "composite"
   steps:
     - name: Send Slack notification
+      if: ${{ inputs.slack_func == 'slack_format_success_message' }}
       shell: bash
       run: |
         workflow_url="https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}"
@@ -31,3 +38,21 @@ runs:
         | curl -s --fail-with-body -d@- "${{ inputs.SLACK_WEB_HOOK_URL }}"
         ${{ inputs.packages_json }}
         JSON
+
+    - name: Send Failure Slack notification
+      if: ${{ inputs.slack_func == 'slack_format_failure_message' }}
+      run: |
+        workflow_url="https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}"
+        footer="Repository: ${{ github.repository }} | Commit: \`${{ github.sha }}\`"
+
+        msg = ${{ inputs.message }}
+        if [ -z "$msg" ]; then
+          echo "Error: message is required"
+          exit 1
+        fi
+
+        . ${GITHUB_WORKSPACE}/.github/actions/common/func.sh
+
+
+        slack_format_failure_message "$msg for Redis: ${{ inputs.release_tag || 'unknown'}} (${{ inputs.env }})" "$workflow_url" "$footer" \
+        | curl -s --fail-with-body -d@- "${{ secrets.SLACK_WEB_HOOK_URL }}"
diff --git a/.github/actions/upload-packages/action.yml b/.github/actions/upload-packages/action.yml
--- a/.github/actions/upload-packages/action.yml
+++ b/.github/actions/upload-packages/action.yml
@@ -63,6 +63,11 @@ runs:
         echo "Missing required inputs for S3 bucket and region"
         exit 1
       fi
+      if [ -z "${ inputs.run_id }" ]; then
+        echo "Missing required inputs for run_id"
+        exit 1
+      fi
+      echo "Will download artifacts from workflow wth Run ID: ${{ inputs.run_id }}"
 
   # For internal release we have an IAM role that we need to assume
   - name: Configure aws credentials for internal release
diff --git a/.github/workflows/release_publish.yml b/.github/workflows/release_publish.yml
--- a/.github/workflows/release_publish.yml
+++ b/.github/workflows/release_publish.yml
@@ -1,3 +1,4 @@
+# This workflow is part of the Redis OSS release automation process.
 on:
   # push:
   #   branches:
@@ -6,11 +7,17 @@ on:
       release_tag:
         description: 'Release tag to build'
         required: true
+      release_type:
+        description: 'Type of release to upload (public, internal)'
+        required: true
       workflow_uuid:
         description: 'Optional UUID to identify this workflow run'
         required: false
       run_id:
         description: 'Run ID to download artifacts from'
+        required: true
+      release_handle:
+        description: 'JSON string containing release handle information'
         required: true
 
 
@@ -26,23 +33,93 @@ jobs:
       - name: Checkout code
         uses: actions/checkout@v4
 
+      - name: Validate inputs
+        id: validate-inputs
+        run: |
+          if [ "${{ inputs.release_type }}" != "public" ] && [ "${{ inputs.release_type }}" != "internal" ]; then
+            echo "Invalid release_type: ${{ inputs.release_type }}"
+            exit 1
+          fi
+          if [ "${{ inputs.release_type }}" = "public" ]; then
+            env_name="production"
+          else
+            env_name="staging"
+          fi
+          echo "env_name=$env_name" >> $GITHUB_OUTPUT
+
+      - name: Ensure Release Branch
+        id: ensure-branch
+        uses: redis-developer/redis-oss-release-automation/.github/actions/ensure-release-branch@main
+        with:
+          release_tag: ${{ github.event.inputs.release_tag }}
+          allow_modify: false
+          gh_token: ${{ secrets.GITHUB_TOKEN }}
+
+      - name: Parse release handle
+        id: parse-handle
+        uses: ./.github/actions/parse-release-handle
+        with:
+          release_handle: ${{ github.event.inputs.release_handle }}
+
       - name: Upload staging packages
         id: upload
         uses: ./.github/actions/upload-packages
         with:
-          run_id: ${{ github.event.inputs.run_id }}
-          release_type: internal
+          run_id: ${{ steps.parse-handle.outputs.run_id }}
+          release_type: ${{ github.event.inputs.release_type }}
           gh_token: ${{ secrets.GITHUB_TOKEN }}
           APT_SIGNING_KEY: ${{ secrets.APT_SIGNING_KEY }}
           APT_S3_BUCKET: ${{ secrets.APT_S3_BUCKET_STAGING }}
           APT_S3_REGION: ${{ secrets.APT_S3_REGION }}
           APT_S3_IAM_ARN: ${{ secrets.APT_S3_IAM_ARN_STAGING }}
 
-      - name: Send Slack notification
+      - name: Merge back to release branch
+        id: merge-back
+        uses: redis-developer/redis-oss-release-automation/.github/actions/merge-branches-verified@main
+        with:
+          from_branch: ${{ steps.ensure-branch.outputs.release_version_branch }}
+          to_branch: ${{ steps.ensure-branch.outputs.release_branch }}
+          gh_token: ${{ secrets.GITHUB_TOKEN }}
+
+      - name: Create Release info
+        shell: bash
+        run: |
+          cat <<JQ > jq
+          {
+            release_tag: "${{ github.event.inputs.release_tag }}",
+            release_type: "${{ github.event.inputs.release_type }}",
+            run_id: ${{ github.run_id }},
+            packages: .
+          }
+          JQ
+          cat <<RESULT | jq -f jq >result.json
+          ${{ steps.upload.outputs.packages_json }}
+          RESULT
+
+      - name: Upload publish result artifact
+        uses: actions/upload-artifact@v4
+        with:
+          name: release_info
+          path: result.json
+          retention-days: 90
+
+      - name: Send Success Slack notification
         uses: ./.github/actions/slack-notification
         with:
+          slack_func: slack_format_success_message
           release_tag: ${{ github.event.inputs.release_tag }}
           url_prefix: https://redis-test-package-repository.s3.us-east-2.amazonaws.com/deb/pool
-          env: staging
+          env: ${{ steps.validate-inputs.outputs.env_name }}
           packages_json: ${{ steps.upload.outputs.packages_json }}
+          SLACK_WEB_HOOK_URL: ${{ secrets.SLACK_WEB_HOOK_URL }}
+
+      - name: Send Failure Slack notification
+        if: failure()
+        uses: ./.github/actions/slack-notification
+        with:
+          slack_func: slack_format_failure_message
+          release_tag: ${{ github.event.inputs.release_tag }}
+          env: ${{ steps.validate-inputs.outputs.env_name }}
+          packages_json: ${{ steps.upload.outputs.packages_json }}
+          message: ":debian: Debian package upload failed"
           SLACK_WEB_HOOK_URL: ${{ secrets.SLACK_WEB_HOOK_URL }}
